FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore "WebApi/API.csproj" /p:NuGetAudit=false

RUN dotnet publish "WebApi/API.csproj" -c Release -o /app/publish /p:NuGetAudit=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080
ENTRYPOINT ["dotnet", "API.dll"]