FROM node:22 AS build
WORKDIR /app

COPY ClientApp/package*.json ./
RUN npm install

COPY ClientApp/ ./
RUN npm run build -- --configuration=production

FROM nginx:alpine
COPY --from=build /app/dist/client/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]